server:
  port: 8080
  servlet:
    context-path: /security/api/v1
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product-service
    username: admin
    password: admin
  security:
    user:
      name: admin
      password: admin
logging:
  level:
    root: debug
    org.springframework.security.web: DEBUG