spring:

  application:
    name: gateway-service

#  boot:
#    admin:
#      client:
#        url: http://127.0.0.1:9090

  cloud:
#    consul:
#      host: 127.0.0.1
#      port: 8500
#      discovery:
#        enabled: true # Enables service discovery.
#        register: true
##        prefer-ip-address: true
#        health-check-path: /actuator/health
#        health-check-interval: 10s
#        heartbeat:
#          ttl: 20s
    gateway:
#      discovery:
#        locator:
#          enabled: true # Allows the gateway to discover routes from services registered in Service Discovery (Consul).
#          lower-case-service-id: true
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - AddRequestHeader=X-Request-Source, Spring-Cloud-Gateway
            - RewritePath=/webflux/(?<segment>.*), /${segment}


logging:
  level:
    org:
      springframework:
        web: DEBUG
        reactive:
          client: DEBUG
          server: DEBUG
          functional:
            server: DEBUG
            client: DEBUG


#management:
#  endpoints:
#    access:
#      default: unrestricted
#    web:
#      exposure:
#        include: "*"
#      cache:
#        time-to-live: "10s"
#  endpoint:
#    shutdown:
#      access: unrestricted
#    health:
#      show-details: always
#      validate-group-membership: false
#    env:
#      show-values: always
#    info:
#      git:
#        mode: "full"
#      env:
#        enabled: true

server:
  port: 8080
